"""
Run this once to bake RTCore64.sys into a C header.
Usage:  python gen_rtcore_header.py
Outputs: rtcore64_bytes.h  (next to this script)
"""
import os, sys

SYS_PATH = r"C:\Program Files (x86)\MSI Afterburner\Legacy\RTCore64.sys"
OUT_PATH  = os.path.join(os.path.dirname(os.path.abspath(__file__)), "rtcore64_bytes.h")

if not os.path.exists(SYS_PATH):
    print(f"[!] Not found: {SYS_PATH}")
    print("    Edit SYS_PATH at top of this script to point to RTCore64.sys")
    sys.exit(1)

data = open(SYS_PATH, "rb").read()
print(f"[*] Read {len(data)} bytes from {SYS_PATH}")

lines = []
lines.append("/* auto-generated by gen_rtcore_header.py — do not edit */")
lines.append(f"#define RTCORE64_SYS_SIZE {len(data)}")
lines.append("static const unsigned char RTCORE64_SYS_DATA[] = {")

row = []
for i, b in enumerate(data):
    row.append(f"0x{b:02x}")
    if len(row) == 16:
        lines.append("    " + ",".join(row) + ",")
        row = []
if row:
    lines.append("    " + ",".join(row))
lines.append("};")

open(OUT_PATH, "w").write("\n".join(lines) + "\n")
print(f"[+] Written: {OUT_PATH}")
print("[+] Now compile dse_fix_win11.c")
